server:
  port: 8285

spring:
  datasource:
    driver-class-name: org.h2.Driver
    //url: jdbc:h2:C:\Temp\H2\test.mv;MV_STORE=true;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    url: jdbc:h2:mem:inm;MV_STORE=true;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: username
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 2000
      max-lifetime: 10000
      leak-detection-threshold: 2000

file_path:
  "C://Temp/"