server:
  port: 8285

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://PCHUPIN-NOTE:1433;databaseName=diasoft
    username: username
    password: password
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 2000
      max-lifetime: 10000
      leak-detection-threshold: 2000

file_path:
  "C://Temp/"